name: buzzwire
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
# ------------------------------ PACKAGES -------------------------------------------- #
dependencies:
  back_button_interceptor: ^8.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.0.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.7
  extended_nested_scroll_view: ^6.2.1
  firebase_auth: ^5.1.0
  firebase_messaging: ^15.1.6
  floor: ^1.4.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.0
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  riverpod_annotation: ^2.1.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.0.0
  sticky_headers: ^0.3.0+2
  supabase_flutter: ^2.8.2
  url_launcher: ^6.3.0
  uuid: ^4.3.3
  webview_flutter: ^4.7.0

# ------------------------------ PACKAGES END -------------------------------------------- #
# ------------------------------ DEV PACKAGES -------------------------------------------- #
dev_dependencies:
  build_runner: ^2.4.6
  # for flutter floor generator
  floor_generator: ^1.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  # for flutter riverpod generator
  riverpod_generator: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# ------------------------------ DEV PACKAGES END -------------------------------------------- #
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # ------------------------------ LOCAL ASSETS -------------------------------------------- #
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # ------------------------------ LOCAL FONTS -------------------------------------------- #
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Light.ttf
          weight: 300
        - asset: assets/fonts/Merriweather-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Merriweather-Regular.ttf
          weight: 400
        - asset: assets/fonts/Merriweather-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 700
        - asset: assets\fonts\Poppins-BoldItalic.ttf
          weight: 700
          style: italic
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
